name: CI - Integração Contínua

on:
  # gatilho manual (nível 1) - botão "Run workflow"
  workflow_dispatch:
  # gatilho por push na branch principal
  push:
    branches:
      - main
  # gatilho agendado (nível 2) - cron em UTC
  schedule:
    - cron: '0 12 * * *' # diariamente às 12:00 UTC (09:00 BRT)

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # instalação das dependências
      - name: Instalando dependências
        run: npm ci

      # execução dos testes automatizados
      - name: Executando os testes
        run: npm test

      # armazenamento do relatório como artefato da pipeline
      - name: Salvando relatório de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Relatório de Testes
          path: ./mochawesome-report
